version: '3.8'

# Local Development Overrides
# Usage: docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d --build

services:
  rk_db:
    ports:
      - "5432:5432"

  rk_storage:
    ports:
      - "29000:9000"
      - "29001:9001"

  rk_cms:
    ports:
      - "24000:4000"
    environment:
      NEXT_PUBLIC_PORTAL_URL: http://localhost:3000
    command: ["npm", "run", "dev"]

  rk_web:
    ports:
      - "23000:3000"

  rk_worker:
    depends_on:
      - rk_storage
      - rk_redis

  rk_redis:
    ports:
      - "6379:6379"
